@startuml

left to right direction

component [Core] as core
component [Control Panel] as controlPanel
component [Acid Rain Monitor] as acidRainMonitor
component [Air Quality Monitor] as airQualityMonitor
component [Noise Pollution Monitor] as noisePollutionMonitor
component [River Monitor] as riverMonitor
component [Persistence Service] as persistenceService

interface "Resource" as resource
interface "Mainstay" as mainstay

interface "Get Resource" as getResource
interface "Post Resource" as postResource
interface "Get Mainstay" as getMainstay
interface "Post Mainstay" as postMainstay

getResource -- persistenceService
postResource -- persistenceService
getMainstay -- persistenceService
postMainstay -- persistenceService

resource -- core
mainstay -- core

core ..> postResource
core ..> postMainstay

controlPanel ..> getResource
controlPanel ..> getMainstay

controlPanel ..> mainstay
controlPanel ..> resource

acidRainMonitor ..> resource

airQualityMonitor ..> resource

noisePollutionMonitor ..> resource

riverMonitor ..> resource

@enduml
